// Import Lucide React icons
import {
  Plus,
  X,
  Package,
  CheckCircle,
  AlertTriangle,
  Info,
  AlertCircle,
  Zap,
  ArrowUp,
  ArrowDown,
  Folder,
  Video,
  Volume2,
  Grid3X3,
  File,
  Download,
  ArrowRight,
  Users,
  Package2,
  Star,
  DollarSign,
  Trash2,
  ChevronUp as AngleUp,
  ChevronDown as AngleDown,
  ChevronLeft as AngleLeft,
  ChevronRight as AngleRight,
  Edit,
  Check,
  X as CloseLine,
  ChevronDown,
  ChevronUp,
  Send,
  Lock,
  Mail,
  User,
  Calendar,
  Eye,
  EyeOff,
  Clock,
  Copy,
  ChevronLeft,
  UserCircle,
  CheckSquare,
  List,
  Table,
  FileText,
  PieChart,
  Boxes,
  Plug,
  BookOpen,
  Mail as MailLine,
  MoreHorizontal,
  MessageCircle,
  AlertTriangle as AlertHexa,
  AlertCircle as ErrorHexa,
} from 'lucide-react';

// Re-export with original names for compatibility
export {
  AlertHexa as ErrorHexaIcon,
  AlertHexa as AlertHexaIcon,
  MoreHorizontal as MoreDotIcon,
  Download as DownloadIcon,
  File as FileIcon,
  Grid3X3 as GridIcon,
  Volume2 as AudioIcon,
  Video as VideoIcon,
  Zap as BoltIcon,
  Plus as PlusIcon,
  Package as BoxIcon,
  X as CloseIcon,
  CheckCircle as CheckCircleIcon,
  AlertTriangle as AlertIcon,
  Info as InfoIcon,
  AlertCircle as ErrorIcon,
  ArrowUp as ArrowUpIcon,
  Folder as FolderIcon,
  ArrowDown as ArrowDownIcon,
  ArrowRight as ArrowRightIcon,
  Users as GroupIcon,
  Package2 as BoxIconLine,
  Star as ShootingStarIcon,
  DollarSign as DollarLineIcon,
  Trash2 as TrashBinIcon,
  AngleUp as AngleUpIcon,
  AngleDown as AngleDownIcon,
  Edit as PencilIcon,
  Check as CheckLineIcon,
  CloseLine as CloseLineIcon,
  ChevronDown as ChevronDownIcon,
  Send as PaperPlaneIcon,
  Mail as EnvelopeIcon,
  Lock as LockIcon,
  User as UserIcon,
  Calendar as CalenderIcon,
  Eye as EyeIcon,
  EyeOff as EyeCloseIcon,
  Clock as TimeIcon,
  Copy as CopyIcon,
  ChevronLeft as ChevronLeftIcon,
  UserCircle as UserCircleIcon,
  CheckSquare as TaskIcon,
  List as ListIcon,
  Table as TableIcon,
  FileText as PageIcon,
  PieChart as PieChartIcon,
  Boxes as BoxCubeIcon,
  Plug as PlugInIcon,
  BookOpen as DocsIcon,
  MailLine as MailIcon,
  MoreHorizontal as HorizontaLDots,
  ChevronUp as ChevronUpIcon,
  MessageCircle as ChatIcon,
  AngleLeft as AngleLeftIcon,
  AngleRight as AngleRightIcon,
};
